version: '3'
services:
  todo-node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: todo-node
    container_name: todo-node
    volumes:
      - ./:/home/
    environment:
      - MONGO_USERNAME=mongo
      - MONGO_PASSWORD=mongo
      - MONGO_PORT=27017
      - MONGO_HOST=mongo-todo-node:27017
      - PORT=8400
      - ENV=LOCAL
      - URL_FRONT=localhost:4200
      - PROTOCAL_FRONT=http
      - VERSION=local
      - DATE_DEPLOY=Sun 18 Apr 2021 07:29:46 AM CEST
      - EMAIL_HOST=ssl0.ovh.net
      - EMAIL_PORT=465
      - EMAIL_USER=dev-team@tic-nova.com
      - EMAIL_PASS=dev-team0
      - PRIVATE_KEY=YjUzNjIwNzNTjkMyOGM7YgFkGZ5NMDZGMxZWjA2Y2zkxMk2ZWZjYjY2NTIyYzA01OTg05U2ZiNEYZTAzFmNhZj
    ports:
      - 8400:8400
    depends_on:
      - mongo-todo-node
  mongo-todo-node:
    image: mongo:8.0
    container_name: mongo-todo-node
    volumes:
      - mongo-volume-todo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 42080:27017
volumes:
  mongo-volume-todo:
